---

- name: Converge
  hosts: all
  gather_facts: yes

  vars:
    potos_playbook_specs:
      client_name: "Potos Vanilla"
      git_url: 'https://github.com/projectpotos/'
      git_repo: 'ansible-specs-potos'
      git_branch: 'main'
  tasks:
    - name: Get templates
      ansible.builtin.find:
        path: '/potos/specs/templates'
        recurse: yes
        file_type: file
      register: potos_playbook_specs_templates

    - name: Create parent dir for templates
      ansible.builtin.file:
        path: '{{ item | regex_replace("^(.*?)\/specs\/templates(.*?)(\.j2)$", "\1\2") | dirname }}'
        state: 'directory'
        recurse: yes
      loop: '{{ potos_playbook_specs_templates.files | map(attribute="path") | list }}'

    - name: Apply templates
      ansible.builtin.template:
        src: '{{ (((playbook_dir, "../../") | path_join), (item | regex_replace("^\/potos\/specs\/(.*)", "\1"))) | path_join | realpath }}'
        dest: '{{ item | regex_replace("^(.*?)\/specs\/templates(.*?)(\.j2)$", "\1\2") }}'
        owner: root
        group: root
        mode: '0644'
      loop: '{{ potos_playbook_specs_templates.files | map(attribute="path") | list }}'

    - name: Get files to copy
      ansible.builtin.find:
        path: '/potos/specs/files'
        recurse: yes
        file_type: file
      register: potos_playbook_specs_files

    - name: Create parent dir for files
      ansible.builtin.file:
        path: '{{ item | regex_replace("^(.*?)\/specs\/files(.*?)$", "\1\2") | dirname }}'
        state: 'directory'
        recurse: yes
      loop: '{{ potos_playbook_specs_files.files | map(attribute="path") | list }}'

    - name: Copy files
      ansible.builtin.copy:
        src: '{{ (((playbook_dir, "../../") | path_join), (item | regex_replace("^\/potos\/specs\/(.*)", "\1"))) | path_join | realpath }}'
        dest: '{{ item | regex_replace("^(.*?)\/specs\/files(.*?)$", "\1\2") }}'
        owner: root
        group: root
        mode: '0644'
      loop: '{{ potos_playbook_specs_files.files | map(attribute="path") | list }}'

    - name: Get vars to copy
      ansible.builtin.find:
        path: '/potos/specs/vars'
        recurse: yes
        file_type: file
      register: potos_playbook_specs_vars

    - name: Create parent dir for vars
      ansible.builtin.file:
        path: '{{ item | regex_replace("^(.*?)\/specs\/vars(.*?)$", "\1/host_vars/all\2") | dirname }}'
        state: 'directory'
        recurse: yes
      loop: '{{ potos_playbook_specs_vars.files | map(attribute="path") | list }}'

    - name: Copy vars
      ansible.builtin.copy:
        src: '{{ (((playbook_dir, "../../") | path_join), (item | regex_replace("^\/potos\/specs\/(.*)", "\1"))) | path_join | realpath }}'
        dest: '{{ item | regex_replace("^(.*?)\/specs\/vars(.*?)$", "\1/host_vars/all\2") }}'
        owner: root
        group: root
        mode: '0644'
      loop: '{{ potos_playbook_specs_vars.files | map(attribute="path") | list }}'

    - name: Install required collections
      ansible.builtin.command:
        cmd: 'ansible-galaxy collection install -r collections.yml -p /etc/ansible/collections'
        chdir: '/potos'
      changed_when: False
