---

- name: Prepare
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install git
      ansible.builtin.package:
        name:
          - 'git'
          - 'python3-pip'

    - name: Install ansible
      ansible.builtin.shell:  # noqa: command-instead-of-module
        cmd: python3 -m pip install ansible>2.12
      changed_when: false

    - name: Checkout potos playbook
      ansible.builtin.git:
        repo: 'https://github.com/projectpotos/ansible-plays-potos.git'
        dest: '/potos'
        version: 'main'

    - name: Create repo place
      ansible.builtin.file:
        path: '/potos/specs'
        state: directory
        recurse: yes

    - name: Copy repo to container
      ansible.builtin.copy:
        src: '{{ (playbook_dir, "../../") | path_join }}'
        dest: '/potos/specs/'
        owner: root
        group: root
        mode: '0766'
