---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:

    - name: Check if requirements template was cloned
      ansible.builtin.stat:
        path: '/potos/templates/requirements.yml.j2'
      register: out
      failed_when:
        - not out.stat.exists

    - name: Check if collections.yml was cloned
      ansible.builtin.stat:
        path: '/potos/collections.yml'
      register: out
      failed_when:
        - not out.stat.exists
